name: Checks 

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: r-base
        run: sudo apt update && sudo apt install r-base quarto -y
      - name: test
        run: make test
