name: Ubuntu Check
  
on: push

jobs:
  linux-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/vcd2df/crayon:latest
    steps:
    - uses: actions/checkout@v4
    - run: make test
