name: Checks 

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: r-base
        run: sudo apt install r-base
      - name: quarto 
        run: sudo Rscript -e 'install.packages("quarto", repos="https://cloud.r-project.org")'
      - name: test
        run: make test
