name: Checks 

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: apt 
        run: sudo apt install r-base qpdf pdflatex -y
      - name: pip
        run: pip install quarto-cli
      - name: rscript 
        run: sudo Rscript -e 'install.packages("quarto", repos="https://cloud.r-project.org")'
      - name: test
        run: make test
