name: LoseDows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Choco install
      shell: pwsh
      run: choco install qpdf quarto html-tidy
    - name: Rscript quarto
      shell: pwsh
      run: Rscript.exe -e 'install.packages("quarto", repos="https://cloud.r-project.org")'
    - name: Check
      shell: pwsh
      run: R.exe CMD check --no-build-vignettes vcd2df_1.0.1.tar.gz 
