name: LoseDows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Download r-base
      run: curl https://cran.r-project.org/bin/windows/base/R-4.5.1-win.exe -o r-base.exe
    - name: Install R-base
      run: start r-base.exe
    - name: Chocolatey
      run: choco install rtools --force
    - name: R Quarto
      run: Rscript -e 'install.packages("quarto", repos="https://cloud.r-project.org")'
    - name: Build
      run: R.exe CMD build .
    - name: Check
      run: R.exe CMD check --as-cran vcd2df_1.0.1.tar.gz 
