name: LoseDows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Choco qpdf
      shell: pwsh
      run: choco install qpdf html-tidy
    - name: Check
      shell: pwsh
      run: R.exe CMD check --as-cran vcd2df_1.0.1.tar.gz 
