name: LoseDows

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Chocolatey install
      shell: pwsh
      run: choco install qpdf quarto miktex
    - name: qpdf test
      shell: pwsh
      run: qpdf --version
    - name: Quarto test
      shell: pwsh
      run: quarto --version
    - name: LaTeX test
      shell: pwsh
      run: pdflatex --version
    - name: Build
      shell: pwsh
      run: R.exe CMD build .
    - name: Check
      shell: pwsh
      run: R.exe CMD check --as-cran vcd2df_1.0.1.tar.gz 
